version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PORT=8080
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
